# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [3]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [4]:
chipo=pd.read_csv(url, sep='\t')

In [5]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
20,10,1,Chips and Guacamole,NaN,$4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
24,12,1,Izze,[Grapefruit],$3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
28,14,1,Canned Soda,[Dr. Pepper],$1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
...,...,...,...,...,...
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$11.75
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",$11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",$11.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
4596,1826,1,Chips and Guacamole,NaN,$4.45
4597,1826,1,Canned Soft Drink,[Nestea],$1.25
4598,1826,1,Bottled Water,NaN,$1.50
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
4600,1827,1,Chips and Guacamole,NaN,$4.45
4601,1827,1,Canned Soft Drink,[Diet Coke],$1.25
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4605,1828,1,Chips and Guacamole,NaN,$4.45
4606,1828,1,Canned Soft Drink,[Coke],$1.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",$11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4609,1829,1,Canned Soft Drink,[Sprite],$1.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 4. How many products cost more than $10.00?

In [6]:
chipo['item_price'] = chipo['item_price'].replace( '[\$]','', regex=True ).apply(np.float64)

In [12]:
len(chipo[chipo['item_price'] >10].groupby('item_name').count())

31

In [11]:
chipo[chipo['item_price'] >10].item_name.nunique()

31

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [19]:
chipo[['item_price','item_name']].head(5)

   item_price                              item_name
0        2.39           Chips and Fresh Tomato Salsa
1        3.39                                   Izze
2        3.39                       Nantucket Nectar
3        2.39  Chips and Tomatillo-Green Chili Salsa
4       16.98                           Chicken Bowl

### Step 6. Sort by the name of the item

In [22]:
chipo[['item_price','item_name']].sort_values(['item_name'], ascending=[False]).head(5)

      item_price          item_name
3889       16.98  Veggie Soft Tacos
2851        8.49  Veggie Soft Tacos
738        11.25  Veggie Soft Tacos
1395        8.49  Veggie Soft Tacos
2384        8.75  Veggie Soft Tacos

### Step 7. What was the quantity of the most expensive item ordered?

In [33]:
maxprice = chipo[['item_price','item_name']].max()['item_price']

In [34]:
maxprice

44.25

In [30]:
chipo[['item_price','item_name','quantity']].sort_values(['item_price'], ascending=[False]).head(5)

      item_price                     item_name  quantity
3598       44.25  Chips and Fresh Tomato Salsa        15
3480       35.25                 Carnitas Bowl         3
1254       35.00               Chicken Burrito         4
3602       35.00               Chicken Burrito         4
3601       33.75                Veggie Burrito         3

In [43]:
chipo[chipo['item_price'] == maxprice].quantity.sum()

15

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [49]:
len(chipo[chipo['item_name'] == "Veggie Salad Bowl"])

18

### Step 9. How many times people orderd more than one Canned Soda?

In [56]:
len(chipo[(chipo['item_name'] == "Canned Soda") & (chipo['quantity'] > 1)])

20

In [ ]:
chipo.